### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by r00bal** [MateuszFrankowski/goit-react-hw-03-image-finder#1]
https://github.com/MateuszFrankowski/goit-react-hw-03-image-finder/blob/ba4aa9e5af4ebf784fe7d3d8e66463795d7b5adc/src/components/App.jsx#L21-L22

Czy napewno te parametry trzeba trzymać w stanie ? Może wystarczyłoby zaznaczać activeImageId i po resztę sięgać findem z images: [ ... ]  np. 
```
const activeImage  = this.state.images.find(({id}) => activeImageId === id )
const { largeImageURL, webformatURL } = activeImage || { }
```

Zgodnie z zasadą, żeby w stanie trzymać tylko niezbędne rzeczy, bo każda zmiana stanu to przeładowanie komponentu

**Comment by MateuszFrankowski** [comment]
zrobione
